### PR TITLE
Fix newspaper header issues

### LINKED ISSUE #168: Beginning of Chapter 86: Newspaper names are missing.
The problem affects epub and fb2 versions.

### PR DESCRIPTION
**Pull request by entorb**
fixes #168

at @rrthomas : added slight adjustments to the LaTeX code to make .tex -> .html conversion more robust, please check (output should be uploaded [here](https://github.com/rrthomas/hpmor/releases/tag/WorkInProgress) in approx 20 min)

### CODE REVIEW

**Comment by entorb** [comment]
build of branch fails, I assume it is a bug in the pipeline. locally it works:

PDF:
image
HTML/epub:
image

**Comment by rrthomas** [comment]
> build of branch fails, I assume it is a bug in the pipeline. locally it works:

I don't understand where the failure is! In the PR conversation it says "All checks have passed". On the checks page, the balance of red/green implies that 50% of the checks failed. But only one check is shown, and it passed. Further, in the global Actions page, the pipeline run for this PR is shown as green.

Anyway, thanks for fixing this, and the LaTeX changes look fine to me.

**Comment by rrthomas** [comment]
Ah, also the [checks page](https://github.com/rrthomas/hpmor/actions/runs/9526736768) reached directly from the [global actions page](https://github.com/rrthomas/hpmor/actions/workflows/check-pr.yml) shows green and is just one check. It's only the [PR's checks page](https://github.com/rrthomas/hpmor/pull/169/checks) that shows red, and it doesn't show any failed check. Odd.

**Comment by entorb** [comment]
I manually triggered the build action, that one failed. Will now merge and hope that on main branch it works as expected (and locally)

**Pull request merged**
