### PR TITLE
ch117 add punctuation

### PR DESCRIPTION
**Pull request by entorb**

### CODE REVIEW

**Comment by rrthomas** [comment]
My impression is that the lack of punctuation is deliberate. Some other formatting is needed to show that this is Harry's disordered thoughts; perhaps to put it in italics? (Is something similar done elsewhere?)

**Comment by entorb** [comment]
did not find other occurrences of thoughs without punctuation

**Comment by entorb** [comment]
only one similar finding:
https://github.com/rrthomas/hpmor/pull/131

**Comment by rrthomas** [comment]
OK, then what about thoughts in general? Are they usually in quotation marks? I agree that we shouldn't have a unique style in just one place.

**Comment by entorb** [comment]
I now formatted the paragraph using emph, as often used for Harry's thoughts, what do you think?

**Comment by rrthomas** [comment]
I think it's good!

**Pull request merged**
